### PR TITLE
Update actions

### PR DESCRIPTION
**Pull request by nehill197**
Added pkgdown action, updated code coverage action from private to public, updated the R-CMD-check action,  and added README render action.
Also updated the code coverage badge in README.

### CODE REVIEW

**Review by aylapear — APPROVED** [review]
Looks good

**Comment by nehill197** [comment]
Installing the dependencies manually using `remotes::install_deps(dependencies = TRUE)` worked to fix the R-CMD-check action on windows.

**Comment by nehill197** [comment]
Re-requesting review now that actions are passing @aylapear

**Review by aylapear — APPROVED** [review]
Looks good

**Pull request merged**
